dist: trusty
language: cpp
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libwxgtk2.8-dev
      - libwxgtk2.8-dbg

script:
  - cmake -DRORSERVER_CRASHHANDLER:BOOL=ON -DRORSERVER_GUI:BOOL=OFF -DRORSERVER_WITH_ANGELSCRIPT:BOOL=ON -DRORSERVER_WITH_WEBSERVER:BOOL=ON .
  - make -j2

notifications:
  email: false
