language: cpp
sudo: false

compiler:
  - gcc
  - clang

env:
  - ANALYZE=false

addons:
  # The following updates are needed for Travis VM running Ubuntu 12.04 and should be removed when Travis updates their OS
  # update gcc for C++11 support
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8


before_install:
  # show some information about the build host
  - cat /proc/cpuinfo | grep -m1 "model name"  # CPU model
  # use specific compiler version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - chmod +x ./tools/travis/linux/travis.sh
  - chmod +x ./tools/travis/linux/build.sh

script:
  - ./tools/travis/linux/travis.sh

notifications:
  email: false
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#rigsofrods-dev"
    on_success: change
    on_failure: always
    use_notice: true
