language: cpp

compiler:
  - gcc
  - clang

env:
  - ANALYZE=false
  - ANALYZE=true

before_script:
  - chmod +x ./tools/travis/linux/travis.sh
  - chmod +x ./tools/travis/linux/build.sh

  - sudo apt-get install cppcheck

script:
  - ./tools/travis/linux/travis.sh

notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#rigsofrods-dev"
    use_notice: true
    skip_join: true
