sudo: required
services:
  - docker

cache:
    directories:
     - $HOME/.cache

language: C

env:
    matrix:
      - OS=ubuntu DIST=xenial

script:
 - git clone https://github.com/packpack/packpack.git packpack
 - packpack/packpack

after_success:
    'rsync -avP -e "ssh -o StrictHostKeyChecking=no" $(find build/ -name "*.deb") anotherfoxguy@frs.sourceforge.net:/home/pfs/project/rigs-of-rods/CI-build/ror-server'
