language: cpp

compiler:
  - gcc
  - clang

env:
  - ANALYZE=false
  #- ANALYZE=true

addons:
  # The following updates are needed for Travis VM running Ubuntu 12.04 and should be removed when Travis updates their OS
  # update gcc for C++11 support
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-4.8

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - chmod +x ./tools/travis/linux/travis.sh
  - chmod +x ./tools/travis/linux/build.sh

install:
  # only install clang/cppcheck if necessary
  - if [ "$CXX" = "clang++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; sudo apt-get -qq update; sudo apt-get install clang; fi
  - if [ $ANALYZE = "true" ] && [ "$CXX" = "g++" ]; then sudo apt-get install -qq cppcheck; fi

script:
  - ./tools/travis/linux/travis.sh

notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#rigsofrods-dev"
    use_notice: true
    skip_join: true
