name: Build server

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TOOLS_PATH: C:\apps\build-tools\
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - run: echo $env:BUILD_TOOLS_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v4

      - name: Cache conan
        uses: actions/cache@v3
        with:
          key: conan-${{ hashFiles('CMakeLists.txt') }}
          path: ~/.conan/

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: | 
          curl "https://raw.githubusercontent.com/AnotherFoxGuy/ci-scripts/main/install-conan.sh" | sudo bash
          sudo apt-get update
          sudo apt-get -y install ninja-build

      - name: Install dependencies (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: cmake -P {0}
        run: |
          file(MAKE_DIRECTORY $ENV{BUILD_TOOLS_PATH})
          file(DOWNLOAD https://cdn.anotherfoxguy.com/build-tools.zip "$ENV{TMP}/build-tools.zip" SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf "$ENV{TMP}/build-tools.zip" WORKING_DIRECTORY "$ENV{BUILD_TOOLS_PATH}")

      - name: Configure
        run: cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DUSE_PACKAGE_MANAGER=ON .

      - name: Build
        run: ninja

      - name: Upload bin folder
        uses: actions/upload-artifact@v4
        with:
          name: ror-server-${{ matrix.os }}
          path: bin
